kind = "DojoContract"
class_hash = "0x7bd0a0caef2c03408a89540eb6e2918e2fe59044893fdefe2e631312ea1b68d"
original_class_hash = "0x7bd0a0caef2c03408a89540eb6e2918e2fe59044893fdefe2e631312ea1b68d"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"
