[world]
kind = "WorldContract"
class_hash = "0x1498dd1197805ec05d37da956d0fc568023a4c25578b0523b4f4f0d0e4f16c2"
original_class_hash = "0x1498dd1197805ec05d37da956d0fc568023a4c25578b0523b4f4f0d0e4f16c2"
abi = "abis/deployments/dojo-world.json"
address = "0x2c8633f80cbeb14ed6d8b24f82fb465c9c1e0574ee40897f7188b569908337f"
transaction_hash = "0x6a552a89cdce98596f295f34050e5e9aec726831372fb2c47e6e30659d0056a"
block_number = 3
seed = "dojo_starter"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/base/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x64db432a705a2831caaca5fcea6766af66c19b1897aa94b118429dae5da2380"
class_hash = "0x3789ded2f1522b5893d82c51dd7b51303e9fc9f78cd9d15421096c5e45e5855"
original_class_hash = "0x3789ded2f1522b5893d82c51dd7b51303e9fc9f78cd9d15421096c5e45e5855"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "abis/deployments/contracts/dojo_starter-actions-7a1c7102.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_starter-actions"
manifest_name = "dojo_starter-actions-7a1c7102"

[[models]]
kind = "DojoModel"
class_hash = "0x35c13bdb9159b896863c212b7343fca5f0f0db80c7cb9cea0002ecb1d1f41ad"
original_class_hash = "0x35c13bdb9159b896863c212b7343fca5f0f0db80c7cb9cea0002ecb1d1f41ad"
abi = "abis/deployments/models/dojo_starter-DirectionsAvailable-77844f1f.json"
tag = "dojo_starter-DirectionsAvailable"
manifest_name = "dojo_starter-DirectionsAvailable-77844f1f"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "directions"
type = "Array<Direction>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2ceff56a9aa56e9048925d52aaf6fe51c560ec1435e2ace85f90e1f91970074"
original_class_hash = "0x2ceff56a9aa56e9048925d52aaf6fe51c560ec1435e2ace85f90e1f91970074"
abi = "abis/deployments/models/dojo_starter-Moved-504403e5.json"
tag = "dojo_starter-Moved"
manifest_name = "dojo_starter-Moved-504403e5"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x13e6c0db807528a9210cf01c6938ca7076ef9683961258e0ee11cb8bbd3cddf"
original_class_hash = "0x13e6c0db807528a9210cf01c6938ca7076ef9683961258e0ee11cb8bbd3cddf"
abi = "abis/deployments/models/dojo_starter-Moves-2a29373f.json"
tag = "dojo_starter-Moves"
manifest_name = "dojo_starter-Moves-2a29373f"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models.members]]
name = "can_move"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5b76d1e991daee4bb9cf7911c5398a629e84fafdbc3f2713fa6a9eef3000e50"
original_class_hash = "0x5b76d1e991daee4bb9cf7911c5398a629e84fafdbc3f2713fa6a9eef3000e50"
abi = "abis/deployments/models/dojo_starter-Position-2ac8b4c1.json"
tag = "dojo_starter-Position"
manifest_name = "dojo_starter-Position-2ac8b4c1"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
