kind = "DojoModel"
class_hash = "0x2ceff56a9aa56e9048925d52aaf6fe51c560ec1435e2ace85f90e1f91970074"
original_class_hash = "0x2ceff56a9aa56e9048925d52aaf6fe51c560ec1435e2ace85f90e1f91970074"
abi = "manifests/dev/abis/base/models/dojo_starter-Moved-504403e5.json"
tag = "dojo_starter-Moved"
manifest_name = "dojo_starter-Moved-504403e5"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "direction"
type = "Direction"
key = false
