kind = "DojoModel"
class_hash = "0x68f4ff25137df7943a4410b72b00b80461d236b0d33e5bef5de2247a6ba7c85"
original_class_hash = "0x68f4ff25137df7943a4410b72b00b80461d236b0d33e5bef5de2247a6ba7c85"
abi = "manifests/dev/abis/base/models/dojo_starter_models_moves_directions_available.json"
name = "dojo_starter::models::moves::directions_available"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "directions"
type = "Array<u8>"
key = false
