kind = "DojoModel"
class_hash = "0x34dfd2dc5076a3fc4999079588c17db90d506f9925d6ede6c353e1ea4d0cf6f"
original_class_hash = "0x34dfd2dc5076a3fc4999079588c17db90d506f9925d6ede6c353e1ea4d0cf6f"
abi = "manifests/dev/base/abis/models/dojo_starter-Moves-2a29373f.json"
tag = "dojo_starter-Moves"
manifest_name = "dojo_starter-Moves-2a29373f"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false

[[members]]
name = "can_move"
type = "bool"
key = false
