kind = "DojoModel"
class_hash = "0x488613c8e3854add0667f4096f45a7d15202d1bd68e0c5b552e9030e282dea7"
original_class_hash = "0x488613c8e3854add0667f4096f45a7d15202d1bd68e0c5b552e9030e282dea7"
abi = "manifests/dev/base/abis/models/dojo_starter-Moved-504403e5.json"
tag = "dojo_starter-Moved"
manifest_name = "dojo_starter-Moved-504403e5"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "direction"
type = "Direction"
key = false
